### ISSUE TITLE
Menu bar

### ISSUE THREAD

**Issue by MisterL33** [MisterL33/NauticApp#1]
Lorsque l'on clic sur un lien provenant du router, la page ciblée se charge bien, mais toutes les routes cliquable s'affichent en haut de la page, il faut faire en sorte de les afficher sur une barre latérale à gauche de la page.

**Comment by Wizyma** [comment]
follow the issues guideline : https://github.com/necolas/issue-guidelines/blob/master/CONTRIBUTING.md#bugs
