### ISSUE TITLE
Redirection après login facebook

### ISSUE THREAD

**Issue by MisterL33** [MisterL33/NauticApp#2]
Je viens d'installer le module react-navigation, qui permet de gérer les changement d'écrans (screens) et les animations associés. 

Ce module est déclaré dans mon src/router.js.

react-navigation marche très bien lorsqu'on utilise des boutons, mais j'ai un problème pour la redirection, je voudrais rediriger l'utilisateur vers une autre page après le login facebook.

Je gère la phase de login dans le fichier src/login.js, c'est une classe simple qui gère firebase et facebook, pour la redirection ce qui m'a l'air le plus facile est de rediriger dans le "onLoginFinished" qui est une fonction appelé quand la connexion est effectué :

  onLoginFinished={
                    (error, result) => {
                        if (error) {
                            alert("Login failed with error: " + result.error);
                        } else if (result.isCancelled) {
                            alert("Login was cancelled");
                        } else {
                            AccessToken.getCurrentAccessToken().then((data) => {
                                const { accessToken } = data
                                this.initUser(accessToken)
                                this.setState({logged: true})
                            })
                            this.props.navigation.navigate('Home')
                        }
                    }
                }

this.props.navigation('Home') permet d'appeler le module react-navigation afin de switch vers la page Home mais renvoi l'erreur suivante : 
Cannot read property 'navigate' of undefined (sachant que cela marche très bien sur les boutons), je pense que c'est un problème de passage de props

**Comment by Wizyma** [comment]
L'indentation du code, se servir des fonctionnalités du markdown !

**Comment by MisterL33** [comment]
Te dérobe pas

**Comment by MisterL33** [comment]
Résolu en passant nav={this.props.navigation} au bouton Login
