### ISSUE TITLE
Google maps - BRANCH DEVELOP

### ISSUE THREAD

**Issue by MisterL33** [MisterL33/NauticApp#4]
La google maps vient du module react-native-maps, implémenté sur la vue loginPage.js

Cette vue est chargée après le login facebook(au pire mettre la vue en principale dans le router.js pour moins de galère).

Il n'y a aucune erreur visible pour la map, le logo google s'affiche mais la map reste jaune, le seul moyen de la forcer à s'afficher est d'ouvrir le menu dev -> toogle inspector sur la page de la map et là elle s'affiche.

Sans cette map on peux dire que mon projet nautique tombe à l'eau

**Comment by Wizyma** [comment]
je regarde ce que je peux faire

**Comment by Wizyma** [comment]
@MisterL33 mais je n'ai pas facebook pour le login ... !

**Comment by MisterL33** [comment]
Change la route principal dans src/router.js : initialRouteName: 'Login' => initialRouteName: 'Home' et tu sera directement sur la page avec la map

________________________________
De : Andrés <notifications@github.com>
Envoyé : mardi 27 février 2018 14:16:30
À : MisterL33/NauticApp
Cc : JULIENNE Laurent; Mention
Objet : Re: [MisterL33/NauticApp] Google maps - BRANCH DEVELOP (#4)


@MisterL33<https://github.com/misterl33> mais je n'ai pas facebook pour le login ... !

**Comment by MisterL33** [comment]
Résolu en utilisant l'émulateur gratuit Genymotion, avec lui la map se charge du premier coup et est même directement "toucheable". 

Pour installer genymotion : https://www.genymotion.com/fun-zone/
Télécharger virtualbox avant de lancer : https://www.virtualbox.org/wiki/Downloads

Créer un terminal virtual avec ces caractéristiques : 

Google Nexus 5X 6.0.0 API 23

Pour lancer l'app il faut donc lancer le terminal puis faire un react-native run-android à la racine du projet.

Au lancement de ce terminal, il y aura un bouton en haut a droite dans le menu (GAPPS), il faut cliquer pour l'installer, ensuite le terminal va redémarrer et proposer d'update google play services, une fois ceci fais et le tout redémarrer, tout marche niquel
